### PR TITLE
🥓 >❤️

### PR DESCRIPTION
**Pull request by chrisj1**

### CODE REVIEW

**Comment by johnnyapol** [comment]
Hmm. I like love and bacon both, so I'm thinking instead of replacing the heart, we have a selection of available phrases and one is randomly chosen. If you implement that, I'll merge this PR.

**Comment by chrisj1** [comment]
Your wish is my command

**Comment by chrisj1** [comment]
@johnnyapol Hows this?

**Comment by johnnyapol** [comment]
Thanks for the contribution!

**Comment by johnnyapol** [comment]
and remember to smash that STAR button if you enjoy the project!

**Comment by chrisj1** [comment]
How could I forget

**Pull request merged**
