### PR TITLE
Introduce new case data algorithm which accounts for the possibility of false negative results

### PR DESCRIPTION
**Pull request by benjaminrsherman**

### CODE REVIEW

**Comment by chrisj1** [comment]
🤔

**Comment by johnnyapol** [comment]
Do we have a formal proof of correctness that this algorithm will provide correct results with a probability p > 0.5?

**Comment by benjaminrsherman** [comment]
> Do we have a formal proof of correctness that this algorithm will provide correct results with a probability p > 0.5?

Yes

**Comment by chrisj1** [comment]
For all epsilon>0 we have that |true-estimated| < epsilon with probability 0<p<=1

**Review by elihschiff — APPROVED** [review]
I can vouch for this math being correct

**Comment by chrisj1** [comment]
@johnnyapol I think you forgot to merge this

**Pull request closed without merging**
